### ISSUE TITLE
veNation shouldn't be rounded in lock page, this misleading

### ISSUE THREAD

**Issue by 10xhunter** [nation3/citizen-app#161]
![image](https://user-images.githubusercontent.com/118603799/204664458-9cbd1f6f-7f15-4a38-bd75-56665949c960.png)

It make me and other people buy Nation 2 times to get 2 veNations

**Comment by aahna-ashina** [comment]
@10xhunter Are you saying that you locked 2.00 `$NATION`, and then your `$veNATION` dropped to 1.99999999?

**Comment by 10xhunter** [comment]
@aahna-ashina Yes, not exactly that number, but definitely less than 2.

There are a lot of pattern like this which is not good.

![image](https://user-images.githubusercontent.com/118603799/205181203-379175f8-bf2f-4067-8f31-b7f00c98614d.png)

**Comment by aahna-ashina** [comment]
https://discord.com/channels/690584551239581708/966360996560142396/1158790435221803080

**Comment by aahna-ashina** [comment]
> https://discord.com/channels/690584551239581708/1140905899788091392/1149996503880966274
> ![lock](https://github.com/nation3/app/assets/95955389/3a563252-e621-4ee9-8f20-97514c2dec7a)

**Comment by aahna-ashina** [comment]
Replaced by #200
