### ISSUE TITLE
The color scheme should be vision-impaired friendly

### ISSUE THREAD

**Issue by 10xhunter** [nation3/citizen-app#162]
It's not good for vision-impaired people to view some of the content as the background color(them color) is too sharp or not contrast enough. Could you please add an option to add a dark mode maybe? 

For example, this page [https://nation3.org/join#carousel](https://nation3.org/join#carousel)

**Comment by aahna-ashina** [comment]
Added #292

**Comment by aahna-ashina** [comment]
#292
