### ISSUE TITLE
Remove allowance revocation from UI

### ISSUE THREAD

**Issue by aahna-ashina** [nation3/citizen-app#251]
Remove the warning message (and related code) from https://app.nation3.org/lock

> ![](https://github.com/nation3/citizen-app/assets/95955389/37acf186-7720-4919-9510-1a938345abd2)

**Comment by AmirGhMohseni** [comment]
https://github.com/nation3/citizen-app/pull/253/commits
39d4aa9dd2afccc8a2d89ce390eca77d3056619a
