### ISSUE TITLE
Division-by-zero error on /liquidity page

### ISSUE THREAD

**Issue by aahna-ashina** [nation3/citizen-app#295]
Mainnet:  https://app.nation3.org/liquidity

> ![](https://github.com/user-attachments/assets/d3b3894c-b485-4d5b-ae9d-15180a76c920)

```javascript
Error: division-by-zero [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-division-by-zero ] (fault="division-by-zero", operation="div", code=NUMERIC_FAULT, version=bignumber/5.7.0)
    at d.makeError (_app-62be13e85bce729f.js:1:113213)
    at d.throwError (_app-62be13e85bce729f.js:1:113333)
```

---

Sepolia:  https://app-sepolia.nation3.org/liquidity

> ![](https://github.com/user-attachments/assets/bcb20450-9101-4d8f-9ad8-93e03ca841ed)

**Comment by brymut** [comment]
Hi @aahna-ashina, could you please confirm that this issue reproducable on sepolia? Not coming up on my end.

**Comment by aahna-ashina** [comment]
> could you please confirm that this issue reproducable on sepolia? Not coming up on my end.

The app is only crashing on Mainnet.  The bug exists on both Mainnet and Sepolia, but triggers only under certain conditions.

**Comment by brymut** [comment]
> > could you please confirm that this issue reproducable on sepolia? Not coming up on my end.
> 
> @brymut The app is only crashing on Mainnet. The bug exists on both Mainnet and Sepolia, but triggers only under certain conditions.

Ahh right, is the solution working out?

**Comment by aahna-ashina** [comment]
https://github.com/nation3/citizen-app/pull/296
